[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Phaseonium = "5a3a09c7-1bd2-40b5-b94f-2570b388f795"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
