# Configuration File

[meta]

description = """
Fast Simulation - just to compile the code
"""

dims = 10
omega = 5.0
dt = 0.01
cycles = 30
T1_initial = 2.0
T2_initial = 2.0

[phaseonium]
phi_hot = 1.9
T_hot = 2.5
phi_cold = 2.1
T_cold = 1.0

[cavity1]
mass = 1.0
surface = 1.0
min_length = 1.0
max_length = 1.01
alpha = 3.1415926535
friction = 0.0
acceleration = 0.0
expanding_force = 2.5
compressing_force = 2.5

[cavity2]
mass = 1.0
surface = 1.0
min_length = 1.0
max_length = 1.01
alpha = 3.1415926535
friction = 0.0
acceleration = 0.0
expanding_force = 2.5
compressing_force = 2.5

[stroke_time]
isochore = 5000
adiabatic = 2000

[samplings]
isochore = 50
adiabatic = 50

[loading]
load_state = false
filename = "state"
past_cycles = 0
