# Configuration File

[meta]
name = "1_new_ode_adiabatic"
description = """"""
dims = 250 
omega = 1.0
dt = 0.01
cycles = 3
T1_initial = 0.05
T2_initial = 0.0

[variables]
force1 = 2.0
force2 = 2.0

[phaseonium]
phi_hot = 1.8
T_hot = 0.08
phi_cold = 6.0
T_cold = 0.01

[cavity1]
mass = 1000000000000000
surface = 5000.0
min_length = 5000.0
max_length = 5500.0
alpha = 0.31415926535
acceleration = 0.0
expanding_force = 1e-12
compressing_force = 0.01

[cavity2]
mass = 0.0
surface = 1.0
min_length = 1.0
max_length = 1.01
alpha = 0
acceleration = 0.0
expanding_force = 2.0
compressing_force = 2.0

[stroke_time]
isochore = 50000
adiabatic = 2000

[samplings]
isochore = 100
adiabatic = 50

[loading]
load_state = false
filename = "state"
past_cycles = 0
